'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const {kinds,statuses,layouts,layoutOf,uid,newState,normalize}=VibePlan;
  const hints={outdoor:'Фото в другой локации: общий кадр на весь разворот или крупный общий кадр вместе с компаниями. Второй вариант подходит, если на локации удалось справедливо разделиться и снять все компании.',personal:'Два личных разворота — свободное наполнение. Свои фотографии, компании, истории или новые постановочные кадры.',teachers:'Выберите один из трёх вариантов. Для своей схемы обсудите расположение с фотографом или загрузите рисунок/пример в окошко и поясните пожелания.',serious:'Заранее выберите место, проверьте доступ и договоритесь об образе всего класса.',fun:'Запишите место и общую задумку. Участники и реквизит должны быть готовы.',portraits:'Стандарт: два человека на странице, четыре на развороте. Оформление выбираем единым для класса: с цитатами или без, с рисунками или без. Свой вариант обсудите с фотографом; опишите его в поле «Название / задумка» или комментарии и добавьте пример.',companies:'Выберите классические компании или фотобудку. Все классические компании размещаются на одном развороте. Заранее определитесь, кто с кем и как снимается: участники основных компаний не повторяются, время распределяем справедливо.',creative:'Каждой творческой компании доступна одна страница: две компании на развороте. Заранее определитесь с составами без повторяющихся участников, идеями, местами и реквизитом. Сложную сцену обсудите с фотографом хотя бы за неделю.',archive:'Ваши телефонные снимки, школьные мемы и личные истории. Добавляйте только то, что хотите сохранить.',photobooth:'Фотобудка — альтернатива классическим компаниям. Все снимаются в одной подготовленной локации: фотограф настраивает камеру и свет, ребята снимают себя с пульта. Кадры собираем на одном развороте.',idea:'Это ваш альбом. Запиши свою идею, добавь пример и поясни, что нужно снять.'};
  let state=newState(), current=2, activeSlot=0, database=null, saveTimer=null, saveChain=Promise.resolve(), busy=false, dirty=false;
  const spread=()=>state.spreads[current];
  const slot=()=>spread().slots[activeSlot];
  function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
  function status(text){$('saveStatus').textContent=text;}
  function position(n,r){Object.assign(n.style,{left:r.x+'%',top:r.y+'%',width:r.w+'%',height:r.h+'%'});}
  let lastDownload=null;
  function download(blob,name){if(lastDownload){URL.revokeObjectURL(lastDownload.url);lastDownload.link.remove();}const url=URL.createObjectURL(blob),a=node('a','download-ready','Файл готов: '+name);a.href=url;a.download=name;a.setAttribute('aria-label','Скачать готовый файл '+name);$('saveToolbarLinks').append(a);lastDownload={url,link:a};a.click();}
  let confirmResolver=null;
  function askConfirm(message){return new Promise(resolve=>{confirmResolver=resolve;$('confirmMessage').textContent=message;$('confirmDialog').showModal();$('confirmCancel').focus();});}
  function finishConfirm(value){const resolve=confirmResolver;confirmResolver=null;$('confirmDialog').close();if(resolve)resolve(value);}
  $('confirmCancel').onclick=()=>finishConfirm(false);
  $('confirmProceed').onclick=()=>finishConfirm(true);
  $('confirmDialog').addEventListener('close',()=>{if(confirmResolver)finishConfirm(false);});
  const filename=()=>('Вайб-'+(state.school||'план')+'-'+(state.mode==='personal'?(state.owner||'личное'):'класс')).replace(/[<>:"/\\|?*]/g,'-');
  async function openDatabase(){return new Promise((resolve,reject)=>{const req=indexedDB.open('vibe-album-plans',1);req.onupgradeneeded=()=>req.result.createObjectStore('drafts');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  async function dbRead(){return new Promise((resolve,reject)=>{const tx=database.transaction('drafts','readonly'),req=tx.objectStore('drafts').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  function persist(){clearTimeout(saveTimer);if(!database){status('Скачай проект для сохранения: хранилище браузера недоступно.');return;}const snapshot=structuredClone(state);saveChain=saveChain.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=database.transaction('drafts','readwrite');tx.objectStore('drafts').put(snapshot,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}));saveChain.then(()=>status('Черновик сохранён на этом устройстве. Для передачи скачай проект или PDF.')).catch(()=>status('Браузер не смог сохранить черновик. Скачай проект, чтобы не потерять работу.'));}
  function changed(){dirty=true;status('Сохраняем черновик на этом устройстве…');clearTimeout(saveTimer);saveTimer=setTimeout(persist,350);renderOverview();renderValidation();}
  function imageElement(image){const img=node('img');img.src=image.src;img.alt=image.name||'Загруженный референс';return img;}
  function mini(sp){const box=node('div','mini-spread');layoutOf(sp).rects.forEach((r,i)=>{const cell=node('div','mini-slot');position(cell,r);if(sp.slots[i].image)cell.append(imageElement(sp.slots[i].image));box.append(cell);});return box;}
  const isUnusedSpread=sp=>sp.kind==='idea'&&!sp.title&&!sp.location&&!sp.comment&&sp.slots.every(slot=>!slot.image&&!slot.comment&&!slot.props);
  function renderOverview(){const list=$('spreadList');list.replaceChildren();state.spreads.forEach((sp,i)=>{if(isUnusedSpread(sp))return;const b=node('button','spread-thumb');b.type='button';b.setAttribute('aria-current',String(i===current));b.setAttribute('aria-label',`Разворот ${i+1}: ${sp.title||kinds[sp.kind]}`);b.append(mini(sp),node('span','',String(i+1).padStart(2,'0')+' / '+(sp.title||kinds[sp.kind])));if(i<2){b.disabled=true;b.setAttribute('aria-label','Разворот '+(i+1)+': личное наполнение, сборка пока недоступна');b.append(node('small','','Личное · пока без сборки'));}else b.onclick=()=>selectSpread(i);list.append(b);});const used=state.spreads.filter(sp=>!isUnusedSpread(sp)).length;$('spreadCount').textContent=used+' из 14 разворотов · включая 2 личных';let addTools=$('addSpreadTools');if(!addTools){addTools=node('div','hero-actions');addTools.id='addSpreadTools';const type=node('select');type.id='addSpreadKind';type.setAttribute('aria-label','Тип нового разворота');Object.entries(kinds).filter(([key])=>key!=='personal').forEach(([key,label])=>{const option=node('option','',label);option.value=key;type.append(option);});type.value='idea';const add=node('button','primary','Добавить разворот');add.type='button';add.id='addSpreadButton';add.onclick=()=>{const i=state.spreads.findIndex(isUnusedSpread);if(i<0)return;const sp=state.spreads[i];sp.kind=type.value;if(sp.kind==='idea')sp.title='Своя идея';current=i;activeSlot=0;renderAll();changed();$('editorTitle').scrollIntoView({behavior:'smooth',block:'start'});};addTools.append(type,add);list.after(addTools);}$('addSpreadButton').disabled=!state.spreads.some(isUnusedSpread);}
  function warnings(){if(state.mode==='personal')return [];const missing=[];[['serious','Серьёзная общая'],['fun','Весёлая общая'],['portraits','Портреты с именами и цитатами']].forEach(([key,label])=>{if(!state.spreads.some(s=>s.kind===key))missing.push('Добавьте раздел: '+label+'.');});if(!state.spreads.some(s=>s.kind==='companies'||s.kind==='creative'))missing.push('Добавьте компании.');state.spreads.forEach((s,i)=>{if(['serious','fun'].includes(s.kind)&&!s.location.trim())missing.push('Разворот '+(i+1)+': укажите место съёмки — '+kinds[s.kind].toLowerCase()+'.');});if(!state.portraitStyle.trim())missing.push('Опишите единый стиль классических портретов.');return missing;}
  function renderValidation(){const box=$('validation');box.replaceChildren();if(state.mode==='personal'){box.append(node('p','','Два личных разворота. Скачай проект и передай представителю класса или фотографу.'));return;}const list=warnings();box.append(node('p','',list.length?'План можно сохранить сейчас. Чтобы план был понятен фотографу, дополни:':'Обязательные разделы, места общих кадров и стиль портретов указаны. План можно передавать фотографу.'));if(list.length){const ul=node('ul');list.forEach(text=>ul.append(node('li','',text)));box.append(ul);}}
  let exampleGalleryData=null;
  function ensureExampleButton(){if($('spreadExampleButton'))return;const b=node('button','quiet','Примеры разворотов');b.id='spreadExampleButton';b.type='button';b.setAttribute('aria-haspopup','dialog');$('sectionHint').after(b);b.onclick=async()=>{const dialog=$('spreadExamplesDialog'),body=$('spreadExamplesBody');body.replaceChildren(node('p','','Загружаем примеры…'));$('spreadExamplesTitle').textContent='Примеры: '+kinds[spread().kind];dialog.showModal();try{if(!exampleGalleryData){const r=await fetch('/assets/vibe-section-examples.json');if(!r.ok)throw Error('Нет ответа');exampleGalleryData=await r.json();}const key=({companies:'groups',creative:'creativeGroups',archive:'memories',photobooth:'memories',outdoor:'fun',idea:'personal-one'})[spread().kind]||spread().kind;const files=exampleGalleryData[key]||exampleGalleryData['personal-one'];let i=0;body.replaceChildren();const image=node('img');image.style.cssText='width:100%;max-height:65vh;object-fit:contain';const controls=node('div','hero-actions'),prev=node('button','quiet','← Назад'),count=node('span'),next=node('button','quiet','Дальше →');prev.type=next.type='button';const show=()=>{image.src='/assets/archive/'+files[i];image.alt='Пример раздела '+kinds[spread().kind];count.textContent=(i+1)+' / '+files.length;};prev.onclick=()=>{i=(i+files.length-1)%files.length;show();};next.onclick=()=>{i=(i+1)%files.length;show();};controls.append(prev,count,next);body.append(image,controls);show();}catch{body.replaceChildren(node('p','','Примеры сейчас не загрузились. Закройте окно и попробуйте ещё раз — заполнение сохранено.'));}};$('closeSpreadExamples').onclick=()=>$('spreadExamplesDialog').close();$('spreadExamplesDialog').addEventListener('close',()=>b.focus({preventScroll:true}));}
  function renderLayouts(){
   const sp=spread(),list=$('layoutList');list.replaceChildren();
   let choices=layouts.filter(l=>!['outdoor-mix','portrait-four'].includes(l.id));
   if(['serious','fun'].includes(sp.kind)){sp.layout='full';activeSlot=0;choices=[layoutOf(sp)];}
   if(sp.kind==='creative'){sp.layout='two';activeSlot=Math.min(activeSlot,1);choices=[{...layouts.find(l=>l.id==='two'),label:'2 компании · по странице каждой'}];}
   if(sp.kind==='portraits'){sp.layout='portrait-four';activeSlot=Math.min(activeSlot,3);choices=[{...layouts.find(l=>l.id==='portrait-four'),label:'4 человека · по 2 на каждой странице'}];}
   if(sp.kind==='outdoor'){choices=layouts.filter(l=>['full','outdoor-mix'].includes(l.id));if(!choices.some(l=>l.id===sp.layout)){sp.layout='full';activeSlot=0;}}
   if(sp.kind==='teachers')choices=[{...layouts.find(l=>l.id==='two'),label:'Классный руководитель слева · пожелания справа'},{...layouts.find(l=>l.id==='three-left'),label:'Классный руководитель и пожелания слева · предметники и директор справа'},{...layouts.find(l=>l.id==='full'),label:'Своя схема · обсудить с фотографом'}];
   choices.forEach(l=>{const b=node('button','layout-button');b.type='button';b.setAttribute('aria-label',l.label);b.setAttribute('aria-pressed',String(l.id===sp.layout));b.append(mini({...sp,layout:l.id,slots:Array.from({length:8},()=>({image:null}))}),node('span','',l.label));b.onclick=()=>{sp.layout=l.id;activeSlot=Math.min(activeSlot,l.rects.length-1);if(sp.kind==='teachers'){const labels=l.id==='two'?['Фото классного руководителя','Пожелания классного руководителя']:l.id==='three-left'?['Фото классного руководителя','Пожелания классного руководителя','Предметники и директор']:['Своя схема: обсудите с фотографом или загрузите пример расположения'];labels.forEach((label,i)=>{if(!sp.slots[i].comment)sp.slots[i].comment=label;});}renderEditor();changed();};list.append(b);});
  }
  function renderCanvas(target,sp,interactive=false){target.replaceChildren();layoutOf(sp).rects.forEach((r,i)=>{const cell=node(interactive?'button':'div','photo-slot'+(interactive&&i===activeSlot?' active':''));position(cell,r);if(interactive){cell.type='button';cell.setAttribute('aria-label','Окошко '+(i+1)+(sp.slots[i].image?': '+sp.slots[i].image.name:': добавить изображение'));cell.setAttribute('aria-pressed',String(i===activeSlot));cell.onclick=()=>{activeSlot=i;renderCanvas($('spreadCanvas'),spread(),true);renderSlot();$('slotEditor').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};cell.ondragover=e=>{e.preventDefault();};cell.ondrop=async e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)await uploadSlot(file,sp,i);};}if(sp.slots[i].image)cell.append(imageElement(sp.slots[i].image));else cell.append(node('span','empty-slot',interactive?'Добавить':'Будущий кадр'));cell.append(node('span','slot-number',String(i+1)));target.append(cell);});}
  function renderParked(){const box=$('parkedImages');box.replaceChildren();const count=layoutOf(spread()).rects.length;const extras=spread().slots.map((s,i)=>({s,i})).filter(({s,i})=>i>=count&&(s.image||s.comment||s.props));if(!extras.length)return;box.append(node('p','','Сохранены за пределами выбранной схемы. Выбери схему с большим числом окошек, чтобы вернуть их на разворот.'));extras.forEach(({s,i})=>{const b=node('button');b.type='button';if(s.image)b.append(imageElement(s.image));b.append(document.createTextNode('Окошко '+(i+1)));b.onclick=()=>{spread().layout='eight';activeSlot=i;renderEditor();changed();};box.append(b);});}
  function renderSlot(){const s=slot();$('slotTitle').textContent='Окошко '+(activeSlot+1);$('slotFilename').textContent=s.image?s.image.name+' · уменьшенная копия для плана':'Можно оставить пустым и описать кадр словами.';$('slotComment').value=s.comment;$('slotProps').value=s.props;$('slotUse').value=s.use;$('slotStatus').value=s.status;$('slotDate').value=s.date;$('removeImage').disabled=!s.image;$('slotMove').replaceChildren();layoutOf(spread()).rects.forEach((r,i)=>{const op=node('option','',i===activeSlot?'На своём месте':'Окошко '+(i+1));op.value=i;$('slotMove').append(op);});$('slotMove').value=activeSlot;}
  function renderEditor(){const sp=spread();$('editorNumber').textContent='Разворот '+(current+1)+' / '+state.spreads.length;$('editorTitle').textContent=sp.title||kinds[sp.kind];$('spreadKind').replaceChildren();Object.entries(kinds).forEach(([key,label])=>{if(current<2&&key!=='personal'||current>=2&&key==='personal')return;const op=node('option','',label);op.value=key;$('spreadKind').append(op);});$('spreadKind').value=sp.kind;$('spreadKind').disabled=current<2;$('spreadTitle').value=sp.title;$('spreadLocation').value=sp.location;$('spreadComment').value=sp.comment;$('sectionHint').textContent=hints[sp.kind];ensureExampleButton();let companyChoice=$('companyChoice');if(!companyChoice){companyChoice=node('div','hero-actions');companyChoice.id='companyChoice';for(const [kind,label] of [['companies','Классические компании'],['photobooth','Фотобудка']]){const b=node('button','quiet',label);b.type='button';b.dataset.companyKind=kind;b.onclick=()=>{spread().kind=kind;renderEditor();renderOverview();changed();};companyChoice.append(b);}$('sectionHint').after(companyChoice);}companyChoice.hidden=!['companies','photobooth'].includes(sp.kind);companyChoice.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.companyKind===sp.kind)));$('builderIdeaPrompt').hidden=!['creative','companies','idea'].includes(sp.kind);$('moveEarlier').disabled=current<=2;$('moveLater').disabled=current<2||current===state.spreads.length-1;$('previousSpread').disabled=current<=2;$('nextSpread').disabled=current===state.spreads.length-1;renderLayouts();renderCanvas($('spreadCanvas'),sp,true);renderParked();renderSlot();}
  function renderStyle(){const box=$('stylePreview');box.replaceChildren();if(state.styleImage){box.append(imageElement(state.styleImage));const b=node('button','quiet','Убрать референс стиля');b.onclick=()=>{state.styleImage=null;renderStyle();changed();};box.append(b);}}
  function renderAll(){if(isUnusedSpread(state.spreads[current]))current=2;$('projectMode').value=state.mode;$('projectClass').value=state.school;$('projectOwner').value=state.owner;$('studentSurname').value=state.student.surname;$('studentName').value=state.student.givenName;$('studentIdentity').hidden=state.mode!=='personal';$('ownerField').hidden=state.mode==='personal';$('portraitStyle').value=state.portraitStyle;$('styleDetails').hidden=state.mode==='personal';$('importPersonal').hidden=state.mode==='personal';$('personalExampleTools').hidden=true;renderStyle();renderOverview();renderValidation();renderEditor();}
  function selectSpread(i){if(busy||i<2)return;current=i;activeSlot=0;renderOverview();renderEditor();}
  function moveSpread(delta){const next=current+delta;if(current<2||next<2||next>=state.spreads.length)return;[state.spreads[current],state.spreads[next]]=[state.spreads[next],state.spreads[current]];current=next;renderAll();changed();}
  function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Не удалось прочитать изображение.'));r.readAsDataURL(file);});}
  function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Изображение не открывается. Выбери JPG, PNG или WebP.'));im.src=src;});}
  async function prepareImage(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Поддерживаются JPG, PNG и WebP.');if(file.size>30*1024*1024)throw new Error('Выбери изображение меньше 30 МБ.');const im=await loadImage(await fileData(file));const factor=Math.min(1,1600/Math.max(im.naturalWidth,im.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.naturalWidth*factor));canvas.height=Math.max(1,Math.round(im.naturalHeight*factor));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height);return {id:uid(),name:file.name,src:canvas.toDataURL('image/jpeg',.84),width:canvas.width,height:canvas.height,source:{kind:'local',filename:file.name}};}
  async function uploadSlot(file,sp=spread(),index=activeSlot){if(busy)return;busy=true;status('Готовим изображение для плана…');try{const image=await prepareImage(file);sp.slots[index].image=image;if(sp===spread()){activeSlot=index;renderEditor();}changed();}catch(e){status(e.message);}finally{busy=false;$('slotUpload').value='';}}
  async function importFile(file,personal=false){if(!file||busy)return;if(file.size>100*1024*1024){status('Файл слишком большой: предел 100 МБ.');return;}busy=true;try{const candidate=normalize(JSON.parse(await file.text()));if(candidate.mode==='personal'||personal){status('Сборка личных разворотов пока недоступна. Файл сохранён у вас; сейчас можно открыть общий план класса.');return;}for(const s of candidate.spreads){for(const v of s.slots){if(v.image)await loadImage(v.image.src);}}if(candidate.styleImage)await loadImage(candidate.styleImage.src);if(personal){if(candidate.mode!=='personal')throw new Error('Для добавления нужен проект из двух личных разворотов.');if(!await askConfirm('Заменить первые два личных разворота этим проектом? Сначала скачай текущий план, если хочешь сохранить прежние варианты.'))return;state.spreads[0]=candidate.spreads[0];state.spreads[1]=candidate.spreads[1];}else{if(dirty&&!await askConfirm('Открыть другой план вместо текущего? Сначала скачай текущий проект, если хочешь сохранить его отдельно.'))return;state=candidate;}current=2;activeSlot=0;renderAll();changed();}catch(e){status(e instanceof SyntaxError?'Не удалось прочитать файл проекта.':e.message);}finally{busy=false;$('projectFile').value='';$('personalFile').value='';}}
  function renderPreview(){const pages=$('previewPages');pages.replaceChildren();const head=node('p','',(state.school||'Класс не указан')+' · '+(state.owner||'Автор не указан'));pages.append(head);if(state.mode==='class')pages.append(node('p','','Стиль портретов: '+(state.portraitStyle||'Пока не выбран')));state.spreads.forEach((sp,i)=>{const page=node('section','preview-page');page.append(node('h3','',(i+1)+'. '+(sp.title||kinds[sp.kind])));const canvas=node('div','spread-canvas');renderCanvas(canvas,sp);page.append(canvas);page.append(node('p','','Место: '+(sp.location||'не указано')+(sp.comment?'\n'+sp.comment:'')));sp.slots.forEach((s,j)=>{if(j>=layoutOf(sp).rects.length&&!s.image&&!s.comment&&!s.props)return;const info=slotLines(s,j);page.append(node('div','preview-note',info.join('\n')));});pages.append(page);});$('previewDialog').showModal();document.body.classList.add('preview-open');}
  function slotLines(s,j){return [`Окошко ${j+1} · ${s.use==='photo'?'Готовая фотография':'Референс / будущий кадр'} · ${statuses[s.status]}`,s.image?'Файл: '+s.image.name:'Изображение пока не добавлено',s.comment?'Задумка: '+s.comment:'',s.props?'Подготовка: '+s.props:'',s.date?'Планируемая дата: '+s.date:''].filter(Boolean);}
  function canvasPage(){const canvas=document.createElement('canvas');canvas.width=1500;canvas.height=1060;const ctx=canvas.getContext('2d');ctx.fillStyle='#f1eee7';ctx.fillRect(0,0,1500,1060);ctx.fillStyle='#242820';return {canvas,ctx};}
  function fitImage(ctx,im,x,y,w,h){const scale=Math.min(w/im.naturalWidth,h/im.naturalHeight);ctx.drawImage(im,x+(w-im.naturalWidth*scale)/2,y+(h-im.naturalHeight*scale)/2,im.naturalWidth*scale,im.naturalHeight*scale);}
  function wrap(ctx,text,width){const result=[];for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText(line+(line?' ':'')+word).width<=width){line+=(line?' ':'')+word;continue;}if(line){result.push(line);line='';}let part='';for(const char of word){if(ctx.measureText(part+char).width>width&&part){result.push(part);part='';}part+=char;}line=part;}result.push(line);}return result;}
  function pushTextPages(pages,title,paragraphs){let {canvas,ctx}=canvasPage(),y=110;const heading=()=>{ctx.font='bold 32px Arial';ctx.fillText(title,60,60);ctx.font='23px Arial';};heading();for(const paragraph of paragraphs){for(const line of wrap(ctx,paragraph,1370)){if(y>985){pages.push(canvas.toDataURL('image/jpeg',.9));({canvas,ctx}=canvasPage());y=110;heading();}ctx.fillText(line,60,y);y+=33;}y+=18;}pages.push(canvas.toDataURL('image/jpeg',.9));}
  async function exportPdf(){if(busy)return;busy=true;$('downloadPdf').disabled=true;status('Собираем PDF с разворотами и всеми комментариями…');try{const snapshot=structuredClone(state),pages=[];pushTextPages(pages,'ВАЙБ · План альбома',[(snapshot.school||'Класс не указан')+' · '+(snapshot.owner||'Автор не указан'),snapshot.mode==='personal'?'Два личных разворота':'14 разворотов: два личных и двенадцать общих','Это план съёмок и наполнения. Окончательный макет готовится после выбора и ретуши фотографий.',snapshot.mode==='class'?'Единый стиль классических портретов: '+(snapshot.portraitStyle||'пока не выбран'):'Свободное личное наполнение.',...warnings()]);if(snapshot.styleImage){const {canvas,ctx}=canvasPage();ctx.font='bold 32px Arial';ctx.fillText('Референс общего стиля портретов',60,60);fitImage(ctx,await loadImage(snapshot.styleImage.src),60,110,1380,860);pages.push(canvas.toDataURL('image/jpeg',.9));}for(let i=0;i<snapshot.spreads.length;i++){const sp=snapshot.spreads[i],{canvas,ctx}=canvasPage();ctx.font='bold 32px Arial';ctx.fillText((i+1)+'. '+(sp.title||kinds[sp.kind]),60,60);const x=60,y=100,w=1380,h=920;ctx.fillStyle='#fff';ctx.fillRect(x,y,w,h);for(const [j,r] of layoutOf(sp).rects.entries()){const rx=x+w*r.x/100,ry=y+h*r.y/100,rw=w*r.w/100,rh=h*r.h/100;ctx.fillStyle='#e2ded3';ctx.fillRect(rx,ry,rw,rh);if(sp.slots[j].image)fitImage(ctx,await loadImage(sp.slots[j].image.src),rx,ry,rw,rh);else{ctx.fillStyle='#636754';ctx.font='22px Arial';ctx.fillText('Будущий кадр '+(j+1),rx+14,ry+35);}ctx.fillStyle='#f1eee7';ctx.fillRect(rx+3,ry+3,32,28);ctx.fillStyle='#242820';ctx.font='18px Arial';ctx.fillText(String(j+1),rx+12,ry+24);}ctx.fillStyle='#0002';ctx.fillRect(x+w/2-3,y,6,h);pages.push(canvas.toDataURL('image/jpeg',.9));const info=['Раздел: '+kinds[sp.kind],'Место: '+(sp.location||'не указано'),sp.comment?'Комментарий к развороту: '+sp.comment:''];sp.slots.forEach((s,j)=>{if(j>=layoutOf(sp).rects.length&&!s.image&&!s.comment&&!s.props)return;info.push((j>=layoutOf(sp).rects.length?'ВНЕ ВЫБРАННОЙ СХЕМЫ. ':'')+slotLines(s,j).join('\n'));});pushTextPages(pages,'Разворот '+(i+1)+' · План и подготовка',info.filter(Boolean));await new Promise(resolve=>setTimeout(resolve,0));}download(makePdf(pages),filename()+'.pdf');status('PDF готов. Если загрузка не началась, нажми ссылку на файл. Для редактирования сохрани также проект.');}catch(e){status('Не удалось собрать PDF: '+e.message+'. Проект можно скачать отдельно.');}finally{busy=false;$('downloadPdf').disabled=false;}}
  function makePdf(pages){const encoder=new TextEncoder(),chunks=[],offsets=[0];let length=0;const write=v=>{const bytes=typeof v==='string'?encoder.encode(v):v;chunks.push(bytes);length+=bytes.length;};const object=(id,content)=>{offsets[id]=length;write(id+' 0 obj\n');write(content);write('\nendobj\n');};write('%PDF-1.4\n');object(1,'<< /Type /Catalog /Pages 2 0 R >>');object(2,'<< /Type /Pages /Count '+pages.length+' /Kids ['+pages.map((_,i)=>(3+i*3)+' 0 R').join(' ')+'] >>');pages.forEach((canvas,i)=>{const id=3+i*3,raw=atob((typeof canvas==='string'?canvas:canvas.toDataURL('image/jpeg',.9)).split(',')[1]),jpeg=Uint8Array.from(raw,c=>c.charCodeAt(0));object(id,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /XObject << /Im '+(id+1)+' 0 R >> >> /Contents '+(id+2)+' 0 R >>');offsets[id+1]=length;write((id+1)+' 0 obj\n<< /Type /XObject /Subtype /Image /Width 1500 /Height 1060 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+jpeg.length+' >>\nstream\n');write(jpeg);write('\nendstream\nendobj\n');const stream='q 842 0 0 595 0 0 cm /Im Do Q\n';object(id+2,'<< /Length '+encoder.encode(stream).length+' >>\nstream\n'+stream+'endstream');});const xref=length;write('xref\n0 '+offsets.length+'\n0000000000 65535 f \n');for(let i=1;i<offsets.length;i++)write(String(offsets[i]).padStart(10,'0')+' 00000 n \n');write('trailer\n<< /Size '+offsets.length+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF');return new Blob(chunks,{type:'application/pdf'});}
  for(const [id,key] of [['studentSurname','surname'],['studentName','givenName']])$(id).oninput=e=>{state.student[key]=e.target.value;state.owner=[state.student.surname.trim(),state.student.givenName.trim()].filter(Boolean).join(' ');changed();};
  $('projectClass').oninput=e=>{state.school=e.target.value;changed();};$('projectOwner').oninput=e=>{state.owner=e.target.value;changed();};$('portraitStyle').oninput=e=>{state.portraitStyle=e.target.value;changed();};
  $('projectMode').onchange=e=>{e.target.value='class';};
  $('newProject').onclick=async ()=>{if(await askConfirm('Начать новый пустой план? Сначала скачай текущий проект, если хочешь сохранить его отдельно.')){state=newState(state.mode);current=2;activeSlot=0;renderAll();changed();}};
  for(const [id,key] of [['spreadTitle','title'],['spreadLocation','location'],['spreadComment','comment']])$(id).oninput=e=>{spread()[key]=e.target.value;if(key==='title')$('editorTitle').textContent=e.target.value||kinds[spread().kind];changed();};
  $('spreadKind').onchange=e=>{spread().kind=e.target.value;renderEditor();changed();};
  for(const [id,key] of [['slotComment','comment'],['slotProps','props'],['slotUse','use'],['slotStatus','status'],['slotDate','date']])$(id).oninput=e=>{slot()[key]=e.target.value;changed();};
  $('slotMove').onchange=e=>{const target=Number(e.target.value);[spread().slots[activeSlot],spread().slots[target]]=[spread().slots[target],spread().slots[activeSlot]];activeSlot=target;renderEditor();changed();};
  $('slotUpload').onchange=e=>{if(e.target.files[0])uploadSlot(e.target.files[0]);};$('removeImage').onclick=()=>{slot().image=null;renderEditor();changed();};
  $('styleUpload').onchange=async e=>{if(!e.target.files[0]||busy)return;busy=true;try{state.styleImage=await prepareImage(e.target.files[0]);renderStyle();changed();}catch(err){status(err.message);}finally{busy=false;e.target.value='';}};
  $('moveEarlier').onclick=()=>moveSpread(-1);$('moveLater').onclick=()=>moveSpread(1);$('previousSpread').onclick=()=>selectSpread(current-1);$('nextSpread').onclick=()=>selectSpread(current+1);
  $('saveProject').onclick=()=>{if(state.mode==='personal'&&(!state.school.trim()||!state.student.surname.trim()||!state.student.givenName.trim())){status('Перед отправкой укажи класс, фамилию и имя — так твой план не потеряется среди других.');$('studentIdentity').hidden=false;$('studentSurname').focus();return;}download(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()})],{type:'application/json'}),filename()+'.vibe');dirty=false;persist();status('Проект готов с изображениями и комментариями. Если загрузка не началась, нажми ссылку на файл.');};
  $('loadProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=e=>importFile(e.target.files[0]);$('importPersonal').onclick=()=>$('personalFile').click();$('personalFile').onchange=e=>importFile(e.target.files[0],true);
  $('downloadPdf').onclick=exportPdf;$('previewAlbum').onclick=renderPreview;$('closePreview').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('close',()=>{document.body.classList.remove('preview-open');$('previewAlbum').focus();});
  window.addEventListener('pagehide',()=>{if(saveTimer)persist();});
  async function keepLegacyPersonal(plan){
    await new Promise((resolve,reject)=>{const tx=database.transaction('drafts','readwrite');tx.objectStore('drafts').put(plan,'legacy-personal');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});
    const notice=$('legacyPlanNotice');notice.hidden=false;notice.append(node('p','','Старый личный черновик сохранён отдельно. Скачайте его для надёжной копии. Сборка личных страниц пока недоступна.'));const button=node('button','quiet','Скачать старый личный проект');button.type='button';button.onclick=()=>download(new Blob([JSON.stringify(plan)],{type:'application/json'}),'Вайб-личный-черновик.vibe');notice.append(button);
  }
  async function init(){try{database=await openDatabase();const saved=await dbRead();let archived=false;if(saved){const restored=normalize(saved);if(restored.mode==='personal'){await keepLegacyPersonal(restored);archived=true;}else state=restored;}if(!archived){const legacy=await new Promise((resolve,reject)=>{const req=database.transaction('drafts','readonly').objectStore('drafts').get('legacy-personal');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(legacy)await keepLegacyPersonal(normalize(legacy));}status('Черновик на этом устройстве. Для надёжной копии и передачи скачай проект.');}catch{status('Хранилище браузера недоступно. Скачивай проект, чтобы сохранить работу.');}renderAll();}
  init();
})();
