'use strict';
(() => {
 const $=id=>document.getElementById(id),C=VibeCollection,P=VibePlan;
 let collection=C.empty(),database=null,timer=null,saveQueue=Promise.resolve(),busy=false,resolveConfirm=null,lastDownload=null,opener=null;
 const n=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
 const say=text=>$('collectionStatus').textContent=text;
 function confirmAction(title,text){$('collectionConfirmTitle').textContent=title;$('collectionConfirmText').textContent=text;$('collectionConfirm').showModal();$('collectionCancel').focus();return new Promise(resolve=>{resolveConfirm=resolve;});}
 function finishConfirm(value){const resolve=resolveConfirm;resolveConfirm=null;$('collectionConfirm').close();resolve?.(value);}
 $('collectionCancel').onclick=()=>finishConfirm(false);$('collectionProceed').onclick=()=>finishConfirm(true);$('collectionConfirm').addEventListener('close',()=>{if(resolveConfirm)finishConfirm(false);});
 function download(blob,name){if(lastDownload){URL.revokeObjectURL(lastDownload.url);lastDownload.link.remove();}const url=URL.createObjectURL(blob),link=n('a','download-ready','Файл готов: '+name);link.href=url;link.download=name;$('collectionDownload').append(link);lastDownload={link,url};link.click();}
 const safeName=()=>('Вайб-'+(collection.school||'класс')).replace(/[<>:"/\\|?*]/g,'-');
 function store(){clearTimeout(timer);if(!database){say('Черновик не сохраняется в браузере. Скачай сборник, чтобы не потерять планы.');return;}const snapshot=structuredClone(collection);saveQueue=saveQueue.catch(()=>{}).then(()=>new Promise((resolve,reject)=>{const tx=database.transaction('collections','readwrite');tx.objectStore('collections').put(snapshot,'current');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);}));saveQueue.catch(()=>say('Браузер не смог сохранить сборник. Скачай его отдельным файлом.'));}
 function changed(){clearTimeout(timer);timer=setTimeout(store,350);render();}
 function listText(values,fallback){const box=n('td');if(!values.length){box.append(n('span','',fallback));return box;}const ul=n('ul');values.forEach(v=>ul.append(n('li','',v)));box.append(ul);return box;}
 function render(){const students=collection.students,missing=C.missing(collection),expected=C.rosterNames(collection.roster),clarify=students.filter(s=>C.summary(s.plan).issues.length);$('receivedCount').textContent=students.length;$('missingCount').textContent=expected.length?missing.length:'—';$('clarifyCount').textContent=clarify.length;$('missingPanel').hidden=!missing.length;$('missingNames').textContent=missing.join(' · ');$('viewCommon').disabled=!collection.common;$('commonStatus').textContent=collection.common?'Общий план загружен · 12 общих разворотов. Стиль портретов: '+(collection.common.portraitStyle||'нужно уточнить'):'Общий план пока не загружен. Добавь файл из режима «Общий план класса».';$('emptyCollection').hidden=students.length>0;$('studentTable').hidden=!students.length;const search=C.fold($('studentSearch').value),rows=$('studentRows');rows.replaceChildren();let shown=0;students.forEach(entry=>{const name=C.fullName(entry.plan);if(search&&!C.fold(name).includes(search))return;shown++;const info=C.summary(entry.plan),row=n('tr'),who=n('td');who.append(n('b','',name),n('small','',entry.plan.school));const progress=n('td');progress.append(n('span','',info.filled+' / '+info.slots+' окошек'),n('small','',info.issues.length?'Есть вопросы: '+info.issues.length:'План заполнен'));const shooting=n('td');shooting.textContent=info.toShoot?info.toShoot+' будущих кадров':'Нет неснятых задумок';const action=n('td'),button=n('button','quiet','Открыть развороты');button.type='button';button.setAttribute('aria-label','Открыть план: '+name);button.onclick=()=>showPlan(entry.plan,button);action.append(button);row.append(who,progress,shooting,listText(info.locations,'Места не указаны'),listText(info.props,'Подготовка не описана'),action);rows.append(row);});$('noSearchResults').hidden=!students.length||shown>0;}
 function renderFields(){$('collectionSchool').value=collection.school;$('collectionRoster').value=collection.roster;render();}
 function img(image){const el=n('img');el.src=image.src;el.alt=image.name||'Референс';return el;}
 function showPlan(plan,button){opener=button;$('studentTitle').textContent=plan.mode==='personal'?C.fullName(plan):'Общий план · '+plan.school;const box=$('studentPages');box.replaceChildren();if(plan.mode==='class'){box.append(n('p','common-summary','Единый стиль классических портретов: '+(plan.portraitStyle||'не указан')));if(plan.styleImage)box.append(img(plan.styleImage));}const info=C.summary(plan);if(info.issues.length){const issues=n('div','student-issues');issues.append(n('b','','Что уточнить'));const ul=n('ul');info.issues.forEach(text=>ul.append(n('li','',text)));issues.append(ul);box.append(issues);}plan.spreads.forEach((sp,i)=>{if(plan.mode==='class'&&i<2)return;const page=n('section','preview-page');page.append(n('h3','',(i+1)+'. '+(sp.title||P.kinds[sp.kind])));const canvas=n('div','spread-canvas');P.layoutOf(sp).rects.forEach((r,j)=>{const cell=n('div','photo-slot');Object.assign(cell.style,{left:r.x+'%',top:r.y+'%',width:r.w+'%',height:r.h+'%'});if(sp.slots[j].image)cell.append(img(sp.slots[j].image));else cell.append(n('span','empty-slot','Будущий кадр'));cell.append(n('span','slot-number',String(j+1)));canvas.append(cell);});page.append(canvas,n('p','common-summary','Место: '+(sp.location||'не указано')+(sp.comment?'\nКомментарий: '+sp.comment:'')));sp.slots.forEach((s,j)=>{if(j>=P.layoutOf(sp).rects.length&&!s.image&&!s.comment&&!s.props)return;const lines=[`Окошко ${j+1} · ${s.use==='photo'?'Готовое фото':'Референс / нужно снять'} · ${P.statuses[s.status]}`,s.image?'Файл: '+s.image.name:'Изображение не добавлено',s.comment?'Задумка: '+s.comment:'',s.props?'Подготовка: '+s.props:'',s.date?'Дата: '+s.date:'',j>=P.layoutOf(sp).rects.length?'Вне выбранной схемы — нужно разместить.':''].filter(Boolean);const detail=n('div','student-slot',lines.join('\n'));if(j>=P.layoutOf(sp).rects.length&&s.image)detail.append(img(s.image));page.append(detail);});box.append(page);});$('studentDialog').showModal();document.body.classList.add('preview-open');}
 async function checkImages(plan){const images=plan.spreads.flatMap(s=>s.slots.map(v=>v.image).filter(Boolean));if(plan.styleImage)images.push(plan.styleImage);for(const image of images){await new Promise((resolve,reject)=>{const el=new Image();el.onload=resolve;el.onerror=()=>reject(new Error('Не открывается изображение: '+image.name));el.src=image.src;});}}
 async function batchImport(files){if(busy||!files?.length)return;if(files.length>200){say('Выбери не больше 200 файлов за один раз.');return;}busy=true;$('batchFiles').disabled=true;const inputs=[],readingErrors=[];try{for(const [i,file] of [...files].entries()){say('Читаем файлы: '+(i+1)+' / '+files.length);try{if(file.size>100*1024*1024)throw new Error('Файл больше 100 МБ.');const raw=JSON.parse(await file.text()),plan=P.normalize(raw);await checkImages(plan);inputs.push({name:file.name,data:plan});}catch(e){readingErrors.push(file.name+': '+(e instanceof SyntaxError?'Не удалось прочитать проект.':e.message));}}const reviewed=C.review(collection,inputs);reviewed.errors.unshift(...readingErrors);if(reviewed.replacements.length&&!await confirmAction('Обновить ранее полученные планы?','Новые версии заменят старые: '+reviewed.replacements.join(', ')+'. Если старые варианты нужны, сначала скачай сборник.')){say('Загрузка отменена. Прежние планы сохранены.');return;}collection=C.apply(collection,reviewed);renderFields();store();$('importReport').textContent=reviewed.errors.length?'Не добавлены:\n'+reviewed.errors.join('\n'):'';say('Добавлено личных планов: '+reviewed.candidates.length+(reviewed.common?' · общий план загружен':'')+(reviewed.errors.length?' · ошибок: '+reviewed.errors.length:'')+'. Скачай сборник для надёжной копии.');}catch(e){say('Не удалось загрузить планы: '+e.message);}finally{busy=false;$('batchFiles').disabled=false;$('batchFiles').value='';}}
 $('batchFiles').onchange=e=>batchImport(e.target.files);
 $('collectionSchool').onchange=async e=>{const proposed=e.target.value.trim();if(collection.students.length||collection.common){if(C.fold(proposed)!==C.fold(collection.school)){say('В сборнике уже есть планы этого класса. Для другого класса нажми «Другой класс».');e.target.value=collection.school;return;}}collection.school=proposed;changed();};
 $('collectionRoster').oninput=e=>{collection.roster=e.target.value;changed();};$('studentSearch').oninput=render;
 $('viewCommon').onclick=e=>showPlan(collection.common,e.currentTarget);$('closeStudent').onclick=()=>$('studentDialog').close();$('studentDialog').addEventListener('close',()=>{document.body.classList.remove('preview-open');opener?.focus();});
 $('saveCollection').onclick=()=>{download(new Blob([JSON.stringify(collection)],{type:'application/json'}),safeName()+'.vibeclass');store();say('Сборник готов: все планы, изображения и комментарии. Сохрани файл по ссылке ниже.');};
 $('exportCsv').onclick=()=>{download(new Blob([C.csv(collection)],{type:'text/csv;charset=utf-8'}),safeName()+'-подготовка.csv');say('Таблица готова. Её можно открыть в Excel: одна строка на окошко, с идеей, местом, реквизитом и датой.');};
 $('newCollection').onclick=async ()=>{if(busy)return;if((collection.students.length||collection.common||collection.roster)&&!await confirmAction('Начать сбор для другого класса?','Текущий сборник заменится пустым. Скачай его перед переключением, чтобы сохранить планы.'))return;collection=C.empty();renderFields();store();$('importReport').textContent='';say('Новый сборник. Укажи класс или загрузи первый файл.');};
 $('loadCollection').onclick=()=>$('collectionFile').click();$('collectionFile').onchange=async e=>{const file=e.target.files[0];if(!file||busy)return;busy=true;try{if(file.size>250*1024*1024)throw new Error('Сборник больше 250 МБ.');const next=C.normalizeCollection(JSON.parse(await file.text()));if((collection.students.length||collection.common||collection.roster)&&!await confirmAction('Открыть другой сборник?','Он заменит текущий список. Сначала скачай текущий сборник, если хочешь сохранить его отдельно.'))return;collection=next;renderFields();store();say('Сборник открыт. Личных планов: '+collection.students.length+'.');$('importReport').textContent='';}catch(error){say('Сборник не открыт: '+error.message);}finally{busy=false;e.target.value='';}};
 window.addEventListener('pagehide',()=>{if(timer)store();});
 async function init(){try{database=await new Promise((resolve,reject)=>{const req=indexedDB.open('vibe-class-collections',1);req.onupgradeneeded=()=>req.result.createObjectStore('collections');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const saved=await new Promise((resolve,reject)=>{const req=database.transaction('collections','readonly').objectStore('collections').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(saved)collection=C.normalizeCollection(saved);say('Сборник хранится на этом устройстве. Для передачи или резервной копии скачай его.');}catch{say('Хранилище браузера недоступно. Скачивай сборник после загрузки файлов.');}renderFields();}
 init();
})();
