'use strict';
(() => {
 const node=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
 const link=(text,url,cls='')=>{const a=node('a',cls,text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;};
 const picks=[
  {title:'Без идеи',text:'Ребята пришли на съёмку без подготовки — идею и кадр придумывали уже на месте. Здесь примеры того, что получилось.',links:[['Посмотреть, что получилось','https://disk.yandex.ru/d/gvIVnJR_U91jnw'],['Ещё примеры','https://disk.yandex.ru/d/QMiyN5rkjj-awA']]},
  {title:'Увлечения',text:'Спорт, музыка, книги, игры, аниме — что ты не бросишь даже ради подготовки к ЕГЭ?',links:[['Найти своё направление','https://disk.yandex.ru/d/NmGjaYa0ScpbTg']]},
  {title:'Послание себе',text:'Характер, мечта или важная история. Смысл может быть очевиден всем или понятен только тебе.',links:[['Смысловые фотографии','https://disk.yandex.ru/d/aQHaoDm56rrP6A']]},
  {title:'Школьная дурь',text:'Весёлые сцены в знакомых местах. Чтобы потом вспомнить не только школу, но и то, что творилось в вашей голове.',links:[['Школьный креатив','https://disk.yandex.ru/d/dEczQdwI9ooD9Q']]},
  {title:'С заморочками',text:'Продуманные образ, фон, реквизит и идея. Такие кадры требуют времени ещё до съёмки.',links:[['Сложные задумки','https://disk.yandex.ru/d/SyowdH__SxEUBA']]},
  {title:'Цветной свет',text:'Когда настроение хочется создать светом и цветом. Школьное помещение может выглядеть совсем по-другому.',links:[['Примеры со светом','https://disk.yandex.ru/d/9F_zvx56iFrCWw']]},
  {title:'Огонь и эффекты',text:'Примеры ярких постановочных эффектов из архива. Если хочется такой кадр, пришли идею фотографу заранее.',links:[['Посмотреть постановки','https://disk.yandex.ru/d/0bHsLVon0Hgkuw']]}
 ];
 const dialog=node('dialog','ideas-dialog');dialog.id='ideasDialog';dialog.setAttribute('aria-labelledby','ideasTitle');
 const head=node('div','ideas-header'),heading=node('div');heading.append(node('span','eyebrow','Для твоего личного разворота'));const title=node('h2','','Передай себе привет из 11-го.');title.id='ideasTitle';title.tabIndex=-1;heading.append(title);const close=node('button','quiet','Закрыть');close.type='button';close.setAttribute('aria-label','Закрыть идеи');head.append(heading,close);dialog.append(head);
 dialog.append(node('p','ideas-intro','Сохрани характер, увлечения, мечты и школьные приколы. Это твоя память о себе — соревноваться ни с кем не нужно.'));
 const video=node('div','ideas-video');video.append(node('p','','Не дружишь с буковками? Есть видео.'),link('Посмотреть видео фотографа','https://youtu.be/A9WiK-54aTo','ideas-video-link'));dialog.append(video,node('p','ideas-links-note','Видео и подборки откроются в новой вкладке. Твой план останется здесь.'));
 const steps=node('ol','ideas-steps');for(const [label,text] of [['Подумай про себя','Что тебя увлекает? Какая школьная шутка или мечта точно твоя?'],['Посмотри и смешай','Можно повторить пример или взять цвет с одной фотографии, свет с другой, а место выбрать своё.'],['Запиши задумку','В конструкторе добавь референс и пару слов: что повторить, что изменить, какая одежда и реквизит нужны.']]){const item=node('li');item.append(node('b','',label),node('span','',text));steps.append(item);}dialog.append(steps);
 const shortcuts=node('nav','ideas-shortcuts');shortcuts.setAttribute('aria-label','Выбрать направление идеи');const grid=node('div','ideas-grid');picks.forEach(pick=>{const card=node('article','idea-pick');card.append(node('h3','',pick.title),node('p','',pick.text));const actions=node('div','idea-pick-links');pick.links.forEach(([text,url])=>actions.append(link(text,url)));card.append(actions);grid.append(card);const button=node('button','',pick.title);button.type='button';button.onclick=()=>card.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});shortcuts.append(button);});dialog.insertBefore(shortcuts,video);dialog.append(grid);
 const archive=node('div','ideas-archive');archive.append(link('Посмотреть весь архив','https://disk.yandex.ru/d/rRzhcwjwmzYrIA'),node('p','','Здесь старые и новые работы. Можно найти пример в архиве, Pinterest или придумать свой — эти подборки не ограничивают тебя.'));dialog.append(archive);
 const preparation=node('div','ideas-preparation');preparation.append(node('h3','','Дай идее немного времени.'),node('p','','Выдели несколько минут сейчас: пока занимаешься другими делами, мозг ещё докрутит задумку. Для Изи выбирайте идею, которую можно снять в школе с подготовленными вами вещами. Вопросы и дополнительные места заранее обсудите с фотографом.'),node('p','','Если съёмка уже завтра, ты всё равно в деле. Принеси любимую одежду и личные предметы: начнём с них и найдём кадр на месте. И за советом можно написать фотографу без готовой идеи.'));dialog.append(preparation);
 const foot=node('div','ideas-bottom');foot.append(node('p','','На двух личных разворотах могут быть и творческие кадры, и обычные личные фото, и компании с друзьями. Выбираешь ты.'));const action=node('button','accent','Вернуться и записать идею');action.type='button';action.onclick=()=>{returnToInput=Boolean(document.getElementById('slotComment'));dialog.close();if(!returnToInput)window.location.href='builder.html';};foot.append(action);dialog.append(foot);
 document.body.append(dialog);let opener=null,returnToInput=false;
 function open(button){if(dialog.open)return;opener=button;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('ideas-open');title.focus({preventScroll:true});}
 close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.classList.remove('ideas-open');if(returnToInput){const input=document.getElementById('slotComment');input?.scrollIntoView({behavior:'auto',block:'center'});input?.focus({preventScroll:true});}else if(opener?.isConnected)opener.focus({preventScroll:true});returnToInput=false;});
 document.querySelectorAll('[data-open-ideas]').forEach(button=>button.addEventListener('click',()=>open(button)));
 globalThis.VibeIdeas={open};
})();
